// Automatically generated by astro-icon
// 79e40579824a7d30cf3757913bd67f93086e3d4f462cbf95adad984c8c476eda

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "clock"
		| "copy"
		| "ruler"
		| "tag"
		| "user";
}